#!/usr/bin/python
from optparse import OptionParser
import os

from gtfs.loader import load
from gtfs.schedule import Schedule


def main():
    usage = "Usage: %prog [options] gtfs.zip"
    parser = OptionParser(usage)
    parser.add_option("-o", "--output_filename", dest="output_filename")

    options, args = parser.parse_args()

    if len(args) != 1:
        parser.error("No gtfs filename supplied")

    gtfs_file = args[0]

    if options.output_filename:
        output_filename = options.output_filename
    else:
        output_filename = os.path.splitext(os.path.basename(gtfs_file))[0] + ".sqlite3"

    print "Loading GTFS feed to " + output_filename 
    load(gtfs_file, output_filename)

if __name__ == '__main__':
    main()
